# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: practice-agent

stages:
- stage: Build
  displayName: 'Build stage configuration'
  
  jobs:
    - job: 
      steps:
        - task: CmdLine@2
          inputs:
            script: |
              echo "Sleep 10s"
              sleep 10


- stage: DEV
  displayName:
  jobs:
    - job: 
      steps:
      - task: CmdLine@2
        inputs:
          script: 'sudo cp -R /home/ubuntu/myagent/_work/1/s/* /var/www/dev.unofficialmentor.com/'


